### PR TITLE
Fix: support certificate pem type

### PR DESCRIPTION
**Pull request by k4leung4**
Signed-off-by: Kenny Leung <kleung@chainguard.dev>

#### Summary

Change is needed to get fulcio test to pass. See https://github.com/sigstore/fulcio/runs/7935433305?check_suite_focus=true

My understanding is that CertificatePEMType is also valid. If not, tests in fulcio will need to be fixed.
https://github.com/sigstore/fulcio/blob/main/pkg/server/grpc_server_test.go#L383

### CODE REVIEW

**Comment by dekkagaijin** [comment]
Would be good to add a test case

**Comment by k4leung4** [comment]
> Would be good to add a test case

added test

**Review by dekkagaijin — APPROVED** [review]

**Comment by haydentherapper** [comment]
Thanks for making a fix! However, can we revert this? This will cause issues if you try to pass a PEM-encoded certificate, the PKIX parsing will fail.

The Fulcio test is what's wrong, it should be creating a PEM-encoded public key with `PublicKeyPEMType`.

**Comment by haydentherapper** [comment]
Ah, I see why the Fulcio tests broke. A PR added PEM block type checking to return a better error message. Previously, the PEM block type didn't matter, so even though the Fulcio test was constructing invalid test input, the tests still passed.

So yea, the correct fix is just to fix the Fulcio test, and revert this.

**Pull request merged**
