### PR TITLE
Move the ssh signing/verification utilities to sigstore from rekor.

### PR DESCRIPTION
**Pull request by dlorenc**
SSH signing has started to gain momentum with support in git! We have an implementation
in rekor that works, but it probably doesn't belong there. Let's move it here and realign
it with our sigstore signing APIs.

Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by bobcallaway** [comment]
I like this (and am supportive of moving over the rest of `rekor/pki` where it makes sense). I think we would still need a way to generate a canonicalized version of a public key and signature to persist in the log (which is what is missing in `sigstore/sigstore` right now.

**Comment by dlorenc** [comment]
> I like this (and am supportive of moving over the rest of `rekor/pki` where it makes sense). I think we would still need a way to generate a canonicalized version of a public key and signature to persist in the log (which is what is missing in `sigstore/sigstore` right now.

Yeah I don't think we need to move allllll of it over. This one was particularly ripe for a move though because we don't even use the Sign function other than for tests of Verify.

**Review by dekkagaijin — DISMISSED** [review]
LGTM FWIW

**Comment by lukehinds** [comment]
also lgtm, do we need to coordinate a removal PR from rekor?

**Review by lukehinds — APPROVED** [review]

**Comment by dlorenc** [comment]
Thanks for the reminders - cleaned up the last TODOs.

**Comment by dlorenc** [comment]
PTAL, should be good now!

**Review by lukehinds — APPROVED** [review]

**Pull request merged**
