### PR TITLE
update golangci-lint to v1.53.x and add depguard rules

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- update golangci-lint to v1.53.x and add depguard rules

### CODE REVIEW

**Review by haydentherapper — COMMENTED** [review]
What is the purpose of depguard?

**Comment by cpanato** [comment]
> What is the purpose of depguard?

> A Go linter that checks package imports are in a list of acceptable packages. This allows you to allow imports from a whole organization or only allow specific packages within a repository.


I was thinking and I am not sure if we want to have that. What are your thoughts?

**Comment by haydentherapper** [comment]
I think this would make sense more at the org level rather than repo. Because if I want to add a dependency, I’ll just update this list in the same PR. 

I’m hesitant to put this at the org level though since that sounds like a lot of effort to maintain.

**Comment by cpanato** [comment]
> I think this would make sense more at the org level rather than repo. Because if I want to add a dependency, I’ll just update this list in the same PR.
> 
> I’m hesitant to put this at the org level, thought since that sounds like a lot of effort to maintain.

agree and thinking more for now that is just overhead to us, i will drop that change and remove the depguard check, thanks for the review and feedback

**Review by haydentherapper — APPROVED** [review]

**Pull request merged**
