### PR TITLE
Bump TUF root version

### PR DESCRIPTION
**Pull request by haydentherapper**
Also update the embedded targets.

### CODE REVIEW

**Comment by haydentherapper** [comment]
@asraa, I wanted to confirm, these target file names should not be prefixed with their hash, correct? I looked through the code and believe that's accurate, but wanted to double check.

**Comment by haydentherapper** [comment]
fyi @jku, since you had posted an issue about updating tuf metadata

**Comment by asraa** [comment]
> @asraa, I wanted to confirm, these target file names should not be prefixed with their hash, correct? I looked through the code and believe that's accurate, but wanted to double check.

I'm pretty sure these are used to prepopulate the cache, and when you download to a local store TUF clients strip the hash prefix. I would test it out locally too.

**Review by znewman01 — APPROVED** [review]
I would love instructions for doing this change (and for verifying it) to be documented somewhere. Also maybe how frequently we should be doing it and maybe even issues that get automatically filed.

None of that's blocking for now!

**Comment by haydentherapper** [comment]
https://github.com/sigstore/root-signing/issues/817 for tracking automation (across all client codebases too)

To verify, in Cosign, I bumped go-tuf to 0.6.0 and replaced s/s with my local repo. Verified without the replace directive `cosign initialize` fails, with the replace directive `cosign initialize` succeeds.

I've also removed `set_ecdsa` from s/s because we no longer need to support the deprecated verifier.

**Comment by haydentherapper** [comment]
Removing `set_ecdsa` is technically a breaking change, if a client hasn't requested a new root since the generation of v5, since the TUF client will have to load the v2/v3/v4 root keys to verify subsequent roots. That was 10 months ago though. I would say that this change is fine to do.

**Review by znewman01 — APPROVED** [review]
nice!

**Comment by haydentherapper** [comment]
Fixing tests now, this is from removing set_ecdsa...

**Review by znewman01 — APPROVED** [review]

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
