### PR TITLE
Update Azure Key Vault client

### PR DESCRIPTION
**Pull request by malancas**
#### Summary

Update the underlying Azure SDK Key Vault client used by the Azure KMS client. This allows us to use newer functions and client defaults, include request retry defaults used when connecting with the Key Vault.

### CODE REVIEW

**Review by cpanato — DISMISSED** [review]
lgtm

thanks

**Review by hectorj2f — APPROVED** [review]
Lgtm

**Comment by lukehinds** [comment]
@malancas if you can move this out of draft and rebase the conflicts, we can merge this.

**Comment by malancas** [comment]
@lukehinds Thanks, just finished up some last testing and resolved the conflicts. The PR is ready now.

**Review by cpanato — APPROVED** [review]
lgtm
thanks

**Comment by malancas** [comment]
@haydentherapper yes, this is ready

**Pull request merged**
