### PR TITLE
use RSA-PSS instead of RSA-PKCS#1 v1.5 signature scheme

### PR DESCRIPTION
**Pull request by dekkagaijin**
PKCS#1 v1.5 has known attacks

Signed-off-by: Jake Sanders <jsand@google.com>

### CODE REVIEW

**Comment by dlorenc** [comment]
Is this actually used anywhere?

Either way, LGTM.

**Review by dlorenc — APPROVED** [review]

**Comment by dekkagaijin** [comment]
> Is this actually used anywhere?

Not afaik, just want there to be a sane default.

**Comment by dlorenc** [comment]
> Not afaik, just want there to be a sane default.

Thanks!

**Pull request merged**
