### PR TITLE
Add fake signer that implements KMS interface

### PR DESCRIPTION
**Pull request by haydentherapper**
This allows us to test code that uses kms.Get by importing the fake KMS
package.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

#### Ticket Link

Fixes

#### Release Note

```release-note
Added fake KMS signer for testing
```

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @bobcallaway

**Review by hectorj2f — APPROVED** [review]
Lgtm, and it would be useful when adding some tests in cosigned

**Review by dlorenc — APPROVED** [review]

**Comment by haydentherapper** [comment]
Need to make one quick change before this is submitted, I want to provide a way to pass in a private key to the loader. Otherwise if you call kms.Get() repeatedly, you'll get back different key values each time.

**Comment by haydentherapper** [comment]
Added: A bit of a weird way to do it, but I'm passing a marshalled ECDSA private key via the string ref. If the string ref after `fakekms://` is empty, then it'll generate a key for you.

**Comment by haydentherapper** [comment]
You know what, it'd be far easier to just pass the private key in the context. I'll clean this up.

**Comment by haydentherapper** [comment]
Ready for review!

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
