### PR TITLE
ci: enable gofumpt with extra

### PR DESCRIPTION
**Pull request by Dentrax**
Signed-off-by: Furkan <furkan.turkal@trendyol.com>

Ran `$ gofumpt -w -extra .`

```
-w	write result to (source) file instead of stdout
-extra
    	enable extra rules which should be vetted by a human
```

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by dlorenc** [comment]
Looks like this has a new lint issue caused by the change!

**Comment by cpanato** [comment]
hello, any updates on this PR? thanks!

**Comment by Dentrax** [comment]
Can someone please approve? Thanks!

**Comment by cpanato** [comment]
@Dentrax you need to rebase and fix the conflicts :)

**Comment by Dentrax** [comment]
Missed that! Rebased.

**Review by cpanato — APPROVED** [review]
thanks

**Comment by cpanato** [comment]
@Dentrax can you please rebase? just to get the latest from the main branch? thanks

**Comment by cpanato** [comment]
need a new rebase 😓

**Review by dekkagaijin — DISMISSED** [review]

**Comment by cpanato** [comment]
i will do a rebase to we get this merged

**Review by hectorj2f — APPROVED** [review]

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
