### PR TITLE
Adapt to simplified DSSE signing interface

### PR DESCRIPTION
**Pull request by adityasaky**
#### Summary

go-securesystemslib was updated to separate signer and verifier interfaces, as a verifier was unnecessary for the signing operation. This commit updates the dsse package to handle this change. It also switches away from the now deprecated NewMultiEnvelopeSigner. These changes should not impact consumers of sigstore/sigstore. See: https://github.com/secure-systems-lab/go-securesystemslib/pull/57

#### Release Note

NONE

#### Documentation

NONE

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]
lgtm

**Review by cpanato — APPROVED** [review]
thank you

**Comment by adityasaky** [comment]
Thanks! Would it be possible to cut a release? I think consumers of both sigstore/sigstore and go-securesystemslib will need to update both simultaneously.

**Comment by cpanato** [comment]
will do tomorrow most likely, have a few other things to merge before that

**Comment by adityasaky** [comment]
Got it, thanks!

**Comment by cpanato** [comment]
@adityasaky release here: https://github.com/sigstore/sigstore/releases/tag/v1.8.0

**Comment by adityasaky** [comment]
Thank you!

**Pull request merged**
