### PR TITLE
Fuzz - Fixed the panic that was caused by incorrect data

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Fixed the issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42466

### CODE REVIEW

**Comment by bobcallaway** [comment]
@naveensrinivasan can you amend the commit with the DCO sign off and I will merge this? Thanks!

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan can you amend the commit with the DCO sign off and I will merge this? Thanks!

Thanks! I did that. TBH, what value does DCO bring? It is a pain to remember every time to do it.

**Comment by bobcallaway** [comment]
Not debating the value, but all Linux Foundation collaborative projects require contributors to execute a DCO.

**Review by dlorenc — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
> Not debating the value, but all Linux Foundation collaborative projects require contributors to execute a DCO.
> […](#)

OSSF is part of the Linux Foundation and the projects there don't require this.

**Comment by dlorenc** [comment]
> OSSF is part of the Linux Foundation and the projects there don't require this.

They're supposed to. See Section 5, IP Policy here: https://cdn.platform.linuxfoundation.org/agreements/openssf.pdf

**Pull request merged**
