### PR TITLE
Make tag,key_ring,key optional for release workflow.

### PR DESCRIPTION
**Pull request by k4leung4**
Signed-off-by: Kenny Leung <kleung@chainguard.dev>

#### Summary

Make tag,key_ring,key optional for release workflow.

This is make it possible to cut releases completely automatically.

The tag will now increment the patch value by one if the release tag is
not specified.
For example:
- 1.5.9 => 1.5.10

Keyring and Key value from GCP project are now hardcoded.

Will remove the input key_ring and key when it dependent workflows are
updated to no longer specify them.

#### Ticket Link

Fixes

towards fixing https://github.com/sigstore/public-good-instance/issues/50

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by k4leung4** [comment]
@cpanato please review.

**Review by dlorenc — APPROVED** [review]

**Review by cpanato — COMMENTED** [review]
for sigstore/sigstore we don't have a cloudbuild, we just tag the repository and create a GitHub release.
i think I did not pay attention much here https://github.com/sigstore/sigstore/pull/325 :(

maybe for sigstore/sigtore we can have a workflow just to create the GH and push the changelog

**Comment by k4leung4** [comment]
> for sigstore/sigstore we don't have a cloudbuild, we just tag the repository and create a GitHub release. i think I did not pay attention much here #325 :(
> 
> maybe for sigstore/sigtore we can have a workflow just to create the GH and push the changelog

Agree. sigstore/sigstore will need it's own release workflow.
This workflow was meant for reuse in cosign, rekor and fulcio.

**Comment by cpanato** [comment]
> > for sigstore/sigstore we don't have a cloudbuild, we just tag the repository and create a GitHub release. i think I did not pay attention much here #325 :(
> > maybe for sigstore/sigtore we can have a workflow just to create the GH and push the changelog
> 
> Agree. sigstore/sigstore will need it's own release workflow. This workflow was meant for reuse in cosign, rekor and fulcio.

ahh true, sorry Monday.... 🤦

**Review by cpanato — APPROVED** [review]

**Pull request merged**
