### PR TITLE
run tests with go1.17 and go1.18

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- run tests with go1.17 and go1.18
follow-up https://github.com/sigstore/sigstore/pull/374/files#r845966876

#### Ticket Link
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
need to update the required checks to replace `unit tests` to `test / unit tests (1.18.x)`/ `test / unit tests (1.17.x)`

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
Any idea why the test didn't run?

**Comment by dlorenc** [comment]
OH - is this because you renamed the test?

**Comment by cpanato** [comment]
> OH - is this because you renamed the test?

yes, need to update the checks, but I don't have admin permission for that (https://github.com/sigstore/sigstore/pull/380#issuecomment-1094296006)

**Pull request merged**
