### PR TITLE
Fuzz tests - tuf

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Fuzz tests for tuf

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@asraa Ran into this while running fuzz tests.


```
warning: starting with empty corpus
fuzz: elapsed: 0s, execs: 0 (0/sec), new interesting: 0 (total: 0)
fuzz: elapsed: 3s, execs: 0 (0/sec), new interesting: 0 (total: 0)
fuzz: minimizing 31-byte failing input file
fuzz: elapsed: 4s, minimizing
--- FAIL: FuzzInitializeTufFromEnv (3.87s)
    --- FAIL: FuzzInitializeTufFromEnv (0.02s)
        fuzz_test.go:25: open /var/folders/pf/bq3t19j505xg4pprmb35ls7r0000gn/T/FuzzInitializeTufFromEnv3710900219/001/targets/artifact.pub: no such file or directory
    
    Failing input written to testdata/fuzz/FuzzInitializeTufFromEnv/771e938e4458e983a736261a702e27c7a414fd660a15b63034f290b146d2f217
    To re-run:
    go test -run=FuzzInitializeTufFromEnv/771e938e4458e983a736261a702e27c7a414fd660a15b63034f290b146d2f217


FAIL
exit status 1
FAIL	github.com/sigstore/sigstore/pkg/tuf	4.044s

Process finished with the exit code 1
```

Am I going in the right direction? Wanted some feedback. I took inspiration from the test code.

**Comment by naveensrinivasan** [comment]
@asraa  Friendly ping

**Comment by haydentherapper** [comment]
Are we ok to close this? I’d like to fuzz TUF, but this requires more thought around which APIs to target.

**Comment by haydentherapper** [comment]
Created an issue, will close this for now.

**Pull request closed without merging**
