### PR TITLE
Migrate to go 1.18 for Fuzzing

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Migrating to go 1.18 for Fuzzing

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@AdamKorcz  Would you be able to some feedback?

**Comment by naveensrinivasan** [comment]
@oliverchang  Could you please review it? I also wanted to ensure this will work with https://github.com/google/oss-fuzz/tree/master/projects/sigstore

**Comment by haydentherapper** [comment]
@jonathanmetzman Is there any benefit to changing to this?

**Comment by AdamKorcz** [comment]
> @AdamKorcz Would you be able to provide some feedback?
> 
> edit:- Especially with respect to running in ossfuzz

Will do.

**Comment by AdamKorcz** [comment]
> @jonathanmetzman Is there any benefit to changing to this?

From the OSS-Fuzz side atm - no. From the perspective of the sigstore contributors - yes, because it will be easier to run the fuzzers locally.

**Review by bobcallaway — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
